export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const FETCH_POST = 'FETCH_POST';
export const LIKE = 'LIKE';
export const COMMENT = 'COMMENT';
export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';
export const FETCH_BY_CREATOR = 'FETCH_BY_CREATOR';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const START_LOADING_CART = "START_LOADING_CART";
export const END_LOADING_CART = "END_LOADING_CART";
export const LOGIN_UPDATE = "LOGIN_UPDATE";
export const FETCH_CART = 'FETCH_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const ORDER_CART = 'ADD_TO_CART';

export const LOGIN_UPDATE_WISHLIST = "LOGIN_UPDATE_WISHLIST";
export const START_LOADING_WISHLIST = "START_LOADING_WISHLIST";
export const END_LOADING_WISHLIST = "END_LOADING_WISHLIST";
export const WISHLIST_CART = 'WISHLIST_CART';
export const FETCH_WISHLIST = 'FETCH_WISHLIST';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const EMPTY_WISHLIST = 'EMPTY_WISHLIST';

export const INSTRUCTORAUTH = 'INSTRUCTORAUTH'
export const START_LOADING_PURCHASED = "START_LOADING_PURCHASED";
export const END_LOADING_PURCHASED = "END_LOADING_PURCHASED";
export const FETCH_PURCHASED = 'FETCH_PURCHASED';
export const EMPTY_PURCHASED = 'EMPTY_PURCHASED';

export const START_LOADING_REVIEW = "START_LOADING_REVIEW";
export const END_LOADING_REVIEW = "END_LOADING_REVIEW";
export const FETCH_REVIEWS = 'FETCH_REVIEWS';
export const EMPTY_REVIEWS = 'EMPTY_REVIEWS';